export const S={data:{},translations:{},images:[],lang:localStorage.getItem('rv-lang')||'ta',theme:localStorage.getItem('rv-theme')||'dark',reduced:localStorage.getItem('rv-reduced')==='true',bookmarks:JSON.parse(localStorage.getItem('rv-bookmarks')||'[]'),api:'https://api-ramaverse.omsaravanabhava.org'};
export const GH=location.hostname.endsWith('github.io'),BASE=GH?'/ramaverse/':'/';
export const base=(p='')=>BASE+p.replace(/^\//,'');
export const path=()=>{let p=location.pathname;if(GH&&p.startsWith('/ramaverse'))p=p.slice(10)||'/';return p.replace(/\/$/,'')||'/'};
export const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const tr=(ta,en)=>S.lang==='ta'?(ta||en):(en||ta);
export const t=(key,fallback='')=>{const v=S.translations[key];return v?tr(v.ta,v.en):(fallback||key)};
export const title=x=>tr(x.tamil_name||x.tamil_text||x.title_ta||x.intent_ta||x.question_ta,x.english_name||x.english_text||x.title_en||x.intent||x.question_en||x.id);
export const summary=x=>tr(x.overview_ta||x.ramayana_context_ta||x.reflection_ta||x.answer_ta||x.story_ta||x.script_ta||x.summary_ta,x.overview_en||x.ramayana_context_en||x.reflection_en||x.answer_en||x.story_en||x.script_en||x.summary_en||'');
export const normal=s=>String(s||'').normalize('NFKD').toLowerCase().replace(/[\u0300-\u036f]/g,'').replace(/[^\p{L}\p{N}\s]/gu,' ').replace(/\s+/g,' ').trim();
export async function load(){for(const n of ['kandas','wisdom','characters','places','guidance','kids','quizzes','audio'])S.data[n]=await fetch(base(`data/${n}.json`)).then(r=>r.ok?r.json():Promise.reject(new Error(`${n}: ${r.status}`)));S.translations=await fetch(base('data/translations.json')).then(r=>r.ok?r.json():{});S.images=await fetch(base('data/image-manifest.json')).then(r=>r.ok?r.json():[])}
export const route=(p,l,extra='')=>`<a data-route href="${base(p)}" class="${path()===('/'+p.replace(/^\//,''))?'active':''}" ${extra}>${l}</a>`;
export const readableStatus=v=>({needs_human_tamil_review:t('trust.reviewPending','Human Tamil review pending'),valmiki_ramayana:t('trust.valmiki','Valmiki Ramayana'),traditional_later_material:t('trust.laterTradition','Later traditional source'),structured:tr('கட்டமைக்கப்பட்ட பதிவு','Structured record'),pending:tr('ஆய்வு நிலுவையில்','Review pending')})[v]||String(v||tr('கட்டமைக்கப்பட்டது','Structured'));
export const imageFor=(x,type='character_portrait')=>{const id=x?.id||x?.entity_id;const exact=S.images.find(a=>a.entity_id===id&&a.asset_type===type);const fallback=S.images.find(a=>a.id==='character-fallback');return exact||fallback||null};
export const imageTag=(x,cls='card-image')=>{const a=imageFor(x);return a?`<img class="${cls}" src="${base(a.local_path)}" alt="${esc(S.lang==='ta'?a.alt_ta:a.alt_en)}" loading="lazy" width="640" height="800">`:''};
function footer(){return `<footer><div class="wrap foot"><div><a data-route class="brand footer-brand" href="${base('')}"><img src="${base('assets/brand/logo-mark.svg')}" alt=""><span>RamaVerse</span></a><p>${t('footer.platform')}</p><a class="btn primary" target="_blank" rel="noopener noreferrer" href="https://play.google.com/store/apps/details?id=com.ramaverse.app">${t('action.googlePlay')}</a></div><div><b>${t('footer.explore')}</b>${route('ramayana',t('stats.kandas'))}${route('characters',t('stats.characters'))}${route('places',t('nav.places'))}${route('journey-map',t('section.journeyMap'))}</div><div><b>${t('footer.experience')}</b>${route('ask',t('nav.ask'))}${route('daily-wisdom',t('section.dailyWisdom'))}${route('kids',t('section.kids'))}${route('learning',t('section.learning'))}</div><div><b>${t('footer.trust')}</b>${['about','privacy','sources','editorial-standards','ai-transparency','content-corrections','accessibility','support','terms'].map(x=>`<a href="${base(x+'.html')}">${x.replaceAll('-',' ')}</a>`).join('')}</div></div></footer>`}
export function shell(body){return `<header><div class="wrap head"><a data-route class="brand" href="${base('')}"><img src="${base('assets/brand/logo-mark.svg')}" alt=""><span>RamaVerse</span></a><button id="menu" class="icon" aria-label="Menu">☰</button><nav id="nav">${route('explore',t('nav.explore'))}${route('ramayana',t('nav.ramayana'))}${route('characters',t('nav.characters'))}${route('places',t('nav.places'))}${route('ask',t('nav.ask'))}${route('audio',t('nav.audio'))}</nav><button id="lang" class="lang-switch" aria-label="${tr('மொழியை மாற்றவும்','Switch language')}"><span class="${S.lang==='ta'?'active':''}">தமிழ்</span><i>|</i><span class="${S.lang==='en'?'active':''}">EN</span></button><button id="theme" class="icon" aria-label="${t('settings.theme')}">${S.theme==='dark'?'☀':'☾'}</button></div></header><main id="main">${body}</main>${footer()}<nav class="mobile">${route('',t('nav.home'))}${route('explore',t('nav.explore'))}${route('ask',t('nav.ask'))}${route('bookmarks',t('nav.library'))}${route('settings',t('nav.settings'))}</nav>`}
export const hero=(en,ta,desc)=>`<section class="page-hero reveal"><div class="eyebrow">RamaVerse Nexus</div><h1>${esc(S.lang==='ta'?(ta||en):en)}<span>${esc(S.lang==='ta'?en:(ta||''))}</span></h1><p>${esc(desc||'')}</p></section>`;
export const card=(x,kind,href='')=>`<${href?'a':'article'} ${href?'data-route':''} ${href?`href="${base(href)}"`:''} class="card reveal" data-search="${esc(normal(JSON.stringify(x)))}">${kind==='characters'?imageTag(x):''}<div class="card-body"><div class="eyebrow">${esc(kind)}</div><h3>${esc(title(x))}</h3>${kind==='characters'?`<div class="secondary-name">${esc(S.lang==='ta'?(x.english_name||''):(x.tamil_name||''))}</div>`:''}<p>${esc(summary(x).slice(0,280))}</p><div class="chips"><span>${esc(readableStatus(x.source_classification))}</span><span>${esc(readableStatus(x.review_status))}</span></div></div></${href?'a':'article'}>`;
export function searchAll(q,limit=30){q=normal(q);if(!q)return[];return Object.entries(S.data).flatMap(([kind,arr])=>arr.map(item=>({kind,item,text:normal(JSON.stringify(item))}))).map(r=>({...r,score:r.text.includes(q)?10:q.split(' ').reduce((n,t)=>n+(r.text.includes(t)?2:0),0)})).filter(r=>r.score).sort((a,b)=>b.score-a.score||String(a.item.id).localeCompare(String(b.item.id))).slice(0,limit)}
export function toggleLang(){S.lang=S.lang==='ta'?'en':'ta';localStorage.setItem('rv-lang',S.lang)}
export function toggleTheme(){S.theme=S.theme==='dark'?'light':'dark';localStorage.setItem('rv-theme',S.theme)}
